FACTS = {
    "War": [
        "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
        "WWII saw the first large-scale use of computers for codebreaking, with machines like the Colossus.",
        "Napoleon was once attacked by a horde of rabbits during a hunting expedition.",
        "The Siege of Leningrad in WWII lasted 872 days, leading to immense civilian suffering.",
        "Ancient Rome's Punic Wars were fought over control of the Mediterranean.",
        "During the Cold War, the U.S. considered using nukes on the Moon to intimidate the USSR.",
        "The Geneva Conventions established international rules of war in 1864.",
        "The Samurai often practiced Zen meditation to prepare mentally for combat.",
        "The Vietnam War introduced the first mass use of helicopters in combat.",
        "War pigeons were used in both World Wars to deliver critical messages.",
        "The Hundred Years’ War lasted 116 years, not 100, between England and France.",
        "Ancient China’s Sun Tzu wrote 'The Art of War,' still studied in military academies.",
        "The medieval trebuchet could hurl objects weighing up to 150 kilograms.",
        "In WWII, 'Operation Mincemeat' used a fake corpse to mislead the Germans.",
        "During the Falklands War, British forces used carrier pigeons despite modern tech.",
        "The War of the Roses inspired elements of 'Game of Thrones.'",
        "Over 70 million people died in WWII, making it the deadliest conflict in history.",
        "The Battle of Stalingrad is often considered a turning point in WWII.",
        "Hannibal famously crossed the Alps with elephants during the Second Punic War.",
        "The American Civil War was the first major conflict captured in photographs.",
        "The Korean War is technically still ongoing due to an armistice, not a peace treaty.",
        "Ancient Spartans trained in warfare from the age of seven.",
        "Trench warfare in WWI created horrific conditions for soldiers, including 'trench foot.'",
        "The Red Cross was founded in response to the carnage of the Battle of Solferino in 1859.",
        "Drones are now a primary tool in modern warfare, revolutionizing combat tactics."
    ],
    "Politics": [
        "Iceland was the first country to have a democratically elected female president in 1980.",
        "George Washington is the only U.S. president unanimously elected by the Electoral College.",
        "The U.N. was founded in 1945 to prevent another global conflict after WWII.",
        "Nelson Mandela spent 27 years in prison before becoming South Africa’s president.",
        "Ancient Athens introduced democracy around 500 BCE.",
        "The Berlin Wall divided East and West Berlin from 1961 to 1989.",
        "The Watergate Scandal led to Richard Nixon’s resignation in 1974.",
        "Winston Churchill won the Nobel Prize in Literature in 1953.",
        "The Magna Carta (1215) is considered a cornerstone of modern democracy.",
        "Fidel Castro gave one of the longest speeches at the U.N., lasting over 4 hours.",
        "The Roman Senate once declared a horse a consul, under Emperor Caligula.",
        "Machiavelli’s *The Prince* shaped modern political philosophy.",
        "Mahatma Gandhi’s peaceful protests helped India gain independence from Britain.",
        "Singapore transitioned from a developing nation to a global hub in 50 years.",
        "Canada became a country on July 1, 1867, through the British North America Act.",
        "The Dalai Lama is a political and spiritual leader exiled from Tibet since 1959.",
        "Finland consistently ranks as the world’s least corrupt nation.",
        "The European Union has 27 member states, with the U.K. leaving in 2020.",
        "The U.S. Constitution is the oldest active constitution in the world.",
        "Argentina and the U.K. fought over the Falkland Islands in 1982.",
        "Julius Caesar's assassination in 44 BCE altered Roman history permanently.",
        "Queen Elizabeth II served as the U.K.'s longest-reigning monarch.",
        "Women in Switzerland gained the right to vote in federal elections in 1971.",
        "The Cuban Missile Crisis brought the world to the brink of nuclear war in 1962.",
        "The first televised U.S. presidential debate was between Nixon and Kennedy in 1960."
    ],
    "Tech": [
        "The first computer virus was created in 1986 and called 'Brain.'",
        "The World Wide Web was invented by Tim Berners-Lee in 1989.",
        "The first smartphone, IBM's Simon, was released in 1994.",
        "ENIAC, the first computer, weighed 27 tons and took up 1,800 square feet.",
        "Tesla’s autopilot system uses AI to navigate roads.",
        "The first email was sent in 1971 by Ray Tomlinson to himself.",
        "Bitcoin was introduced in 2009 by the mysterious Satoshi Nakamoto.",
        "The Apollo 11 computer had less processing power than today’s smartphones.",
        "The first video game, *Pong*, debuted in 1972.",
        "Google started as a research project by Larry Page and Sergey Brin.",
        "The floppy disk was invented in 1967 by IBM.",
        "Apple’s iPhone transformed mobile tech upon its release in 2007.",
        "CAPTCHA was designed to block bots and verify humans online.",
        "The first 3D printer was built in 1983 by Charles Hull.",
        "Wikipedia launched in 2001 and became the largest free encyclopedia.",
        "Tesla’s Gigafactory is one of the largest buildings on Earth by floor area.",
        "The first photo ever taken was captured in 1826 by Joseph Nicéphore Niépce.",
        "Amazon’s first product was books, sold online in 1995.",
        "The term 'robot' comes from a 1921 play by Karel Čapek.",
        "The Mars Rover Perseverance has its own Twitter account.",
        "Moore’s Law predicted that computer processing power would double every two years.",
        "Sony’s Walkman changed how people listened to music on the go.",
        "SpaceX’s Falcon 9 rocket is reusable, a milestone in space exploration.",
        "The world’s first website is still online at CERN’s servers.",
        "QR codes were invented in Japan in 1994 to track car parts."
    ],
    "Sport": [
        "The first Olympic Games were held in 776 BCE in ancient Greece.",
        "Michael Phelps has won the most Olympic gold medals, with a total of 23.",
        "The FIFA World Cup is the most-watched sporting event in the world.",
        "The Tour de France is the oldest and most prestigious cycling race, first held in 1903.",
        "Serena Williams has won more Grand Slam singles titles than any other tennis player in the Open Era.",
        "The Super Bowl is the most-watched annual sports event in the U.S.",
        "Cricket matches can last up to five days in Test formats.",
        "Basketball was invented by James Naismith in 1891.",
        "The fastest recorded tennis serve is 263 km/h (163.4 mph) by Sam Groth in 2012.",
        "Pele is the only player to win three FIFA World Cups.",
        "Rugby originated from a soccer game in 1823 when a player picked up the ball and ran with it.",
        "The first marathon race was inspired by the ancient Greek soldier Pheidippides.",
        "Baseball's World Series has been held since 1903.",
        "The ancient Maya played a ball game called Pok-A-Tok, where losing could be fatal.",
        "Shaquille O'Neal made only one three-point shot in his entire NBA career.",
        "Roger Bannister broke the 4-minute mile barrier in 1954.",
        "Formula 1 drivers experience up to 6G force during high-speed turns.",
        "The Wimbledon tennis tournament has been played since 1877.",
        "The Stanley Cup is the oldest professional sports trophy in North America.",
        "The longest chess game theoretically possible involves 5,949 moves.",
        "The Boston Marathon is the world’s oldest annual marathon, first held in 1897.",
        "Lionel Messi holds the record for most goals in a calendar year, with 91 in 2012.",
        "Ice hockey was first played professionally in Canada in 1902.",
        "The FIFA Women’s World Cup was first held in 1991 in China."
    ],
    "Music": [
        "Mozart started composing music at the age of five.",
        "The Beatles are the best-selling music act of all time, with over 600 million records sold.",
        "The world’s largest music festival is Donauinselfest in Vienna, Austria.",
        "Beethoven was completely deaf when he composed his Ninth Symphony.",
        "Michael Jackson’s *Thriller* is the best-selling album of all time.",
        "The piano was invented in Italy in 1709 by Bartolomeo Cristofori.",
        "Elvis Presley is often referred to as the 'King of Rock and Roll.'",
        "Jimi Hendrix played his guitar upside-down because he was left-handed.",
        "Taylor Swift wrote her entire *Speak Now* album by herself.",
        "The electric guitar was invented in 1931.",
        "The Rolling Stones have been performing for over 60 years.",
        "Queen’s 'Bohemian Rhapsody' was the first music video to air on MTV Europe.",
        "Beyoncé is the most awarded female artist in Grammy history.",
        "Bob Dylan was awarded the Nobel Prize in Literature in 2016.",
        "Freddie Mercury was born in Zanzibar and grew up in India.",
        "K-pop sensation BTS has one of the most active fanbases globally, known as ARMY.",
        "The ukulele originated in Hawaii in the 19th century.",
        "Whitney Houston’s *I Will Always Love You* is one of the best-selling singles of all time.",
        "Lady Gaga’s real name is Stefani Joanne Angelina Germanotta.",
        "The world’s largest opera house is the Metropolitan Opera House in New York City.",
        "Classical composer Antonio Vivaldi was nicknamed the 'Red Priest' for his red hair.",
        "Johnny Cash performed at prisons like Folsom and San Quentin.",
        "Adele’s album *21* is one of the best-selling albums in history.",
        "The saxophone was invented by Adolphe Sax in 1846."
    ],
    "Art": [
        "Leonardo da Vinci’s *Mona Lisa* is the most visited painting in the world.",
        "Vincent van Gogh only sold one painting during his lifetime.",
        "Michelangelo spent four years painting the Sistine Chapel ceiling.",
        "Banksy is one of the most famous anonymous street artists.",
        "The *Starry Night* was painted by Van Gogh while in an asylum.",
        "Pablo Picasso produced over 13,000 paintings in his lifetime.",
        "The *Venus de Milo* is over 2,000 years old and was discovered on a Greek island.",
        "Salvador Dalí designed the logo for Chupa Chups lollipops.",
        "The first modern abstract art was created by Wassily Kandinsky.",
        "Andy Warhol’s *Campbell’s Soup Cans* made him a pop art icon.",
        "The Louvre in Paris is the largest art museum in the world.",
        "Claude Monet’s garden in Giverny inspired his famous *Water Lilies* series.",
        "The Taj Mahal is often called the most beautiful piece of Islamic art.",
        "Frida Kahlo’s self-portraits explore themes of identity and pain.",
        "Edvard Munch’s *The Scream* was inspired by a real-life experience of anxiety.",
        "The ancient cave paintings in Lascaux, France, are over 17,000 years old.",
        "The Statue of Liberty was designed by French sculptor Frédéric Auguste Bartholdi.",
        "Marcel Duchamp’s *Fountain* redefined modern art in 1917.",
        "The Rosetta Stone was key to deciphering Egyptian hieroglyphs.",
        "Sandro Botticelli’s *The Birth of Venus* remains an iconic Renaissance masterpiece.",
        "The Great Wave off Kanagawa by Hokusai is one of the most famous Japanese artworks.",
        "Rembrandt’s *The Night Watch* is celebrated for its dramatic use of light and shadow.",
        "Auguste Rodin’s *The Thinker* was initially part of a larger work, *The Gates of Hell*.",
        "Johannes Vermeer’s *Girl with a Pearl Earring* is often called the 'Mona Lisa of the North.'"
    ],
    "Celebs": [
        "Tom Cruise performs many of his own stunts, including hanging off a plane in *Mission: Impossible*.",
        "Oprah Winfrey was the first African-American female billionaire.",
        "Marilyn Monroe’s real name was Norma Jeane Mortenson.",
        "Keanu Reeves gives away millions to charity and his film crew.",
        "Dwayne 'The Rock' Johnson was a professional wrestler before becoming an actor.",
        "Taylor Swift’s lucky number is 13, and she hides it in her music and videos.",
        "Morgan Freeman got his big break at the age of 50.",
        "Emma Watson graduated from Brown University while acting in movies.",
        "Will Smith turned down the role of Neo in *The Matrix*.",
        "Elon Musk made a cameo in *Iron Man 2* as himself.",
        "Angelina Jolie is a U.N. Goodwill Ambassador and humanitarian advocate.",
        "Johnny Depp collects rare books and artifacts.",
        "Jennifer Lopez was the first Latina actress to earn over $1 million for a film role.",
        "Arnold Schwarzenegger served as the governor of California from 2003 to 2011.",
        "Leonardo DiCaprio is a passionate environmental activist.",
        "Meryl Streep holds the record for the most Oscar nominations of any actor.",
        "Lady Gaga’s meat dress at the VMAs in 2010 became a cultural phenomenon.",
        "Beyoncé’s alter ego on stage is called Sasha Fierce.",
        "David Bowie wrote *Space Oddity* in response to the moon landing.",
        "Rihanna became a billionaire due to her Fenty Beauty line.",
        "Chris Hemsworth trained extensively to play Thor in the Marvel series.",
        "Ariana Grande’s four-octave vocal range has been compared to Mariah Carey’s.",
        "George Clooney once gifted $1 million to each of his 14 closest friends.",
        "Kim Kardashian passed the baby bar exam on her journey to become a lawyer."
    ]
}


SYMBOLS = {
    "Sport": "🏀",
    "Politics": "🌍",
    "Tech": "🖥️",
    "Music": "🎼",
    "Celebs": "💫",
    "Art": "🖼️",
    "War": "⚔️",
    "Random": "🎁",
    "On this Day": "🗃️",
    "On this Day: Birth": "🐣"
}